### ISSUE TITLE
Failed to run example and demo

### ISSUE THREAD

**Issue by richliao** [hshindo/react-nlp#39]
I am getting the following error while I do npm run example or demo

ERROR in ./example/src/index.jsx
Module parse failed: /Users/zhiliao/react/node_modules/react-nlp/example/src/index.jsx Unexpected token (7:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (7:4)
    at Parser.pp$4.raise (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseExprList (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (/Users/zhiliao/react/node_modules/react-nlp/node_modules/webpack/node_modules/acorn/dist/acorn.js:1741:35)
 @ multi jsx

I have all dependencies installed. I can see following folders are under node_modules
Zhis-iMac:node_modules zhiliao$ ls
asap			color-string		iconv-lite		node-fetch		react-dom
clone			core-js			is-stream		npm-debug.log		react-nlp
color			css-element-queries	isomorphic-fetch	object-assign		setimmediate
color-convert		encoding		js-tokens		promise			ua-parser-js
color-name		fbjs			loose-envify		react			whatwg-fetch

Since I don't know react well, I don't even how to trace the problem. Can you shed some lights? I will appreciate it very much. 

Thanks! - Richard

**Comment by hshindo** [comment]
Thank you for your report.
I'll check this out.

**Comment by hshindo** [comment]
Did you run `npm run build`?
If so, could you give me your environment (OS, etc.)?

**Comment by hshindo** [comment]
@richliao
Did you run `npm run build`?
If so, could you give me your environment (OS, etc.)?

**Comment by richliao** [comment]
Thanks for looking at this.

npm run build run successfully - by the way, it failed without running npm init first

my npm version is 3.10.8, I am running on mac Sierra 10.12.3

**Comment by hshindo** [comment]
Maybe update your node version to 7+.
We are using node 7.4

**Comment by richliao** [comment]
upgrade both node and npm to latest version:
node -v
v7.8.0
npm -v
4.4.4

But it still fails at the same error.

**Comment by richliao** [comment]
Problem solved.
